// Bangladeshi scheduled banks (Bangladesh Bank licensed)
export const BD_BANKS: string[] = [
  "Sonali Bank",
  "Janata Bank",
  "Agrani Bank",
  "Rupali Bank",
  "BASIC Bank",
  "Bangladesh Development Bank (BDBL)",
  "Probashi Kallyan Bank",
  "Ansar-VDP Unnayan Bank",
  "Karmasangsthan Bank",
  "Bangladesh Krishi Bank",
  "Rajshahi Krishi Unnayan Bank",
  "Palli Sanchay Bank",
  "AB Bank",
  "Al-Arafah Islami Bank",
  "Bank Asia",
  "BRAC Bank",
  "City Bank",
  "Commercial Bank of Ceylon",
  "Community Bank Bangladesh",
  "Dhaka Bank",
  "Dutch-Bangla Bank",
  "Eastern Bank (EBL)",
  "EXIM Bank",
  "First Security Islami Bank",
  "Global Islami Bank",
  "ICB Islamic Bank",
  "IFIC Bank",
  "Islami Bank Bangladesh",
  "Jamuna Bank",
  "Meghna Bank",
  "Mercantile Bank",
  "Midland Bank",
  "Modhumoti Bank",
  "Mutual Trust Bank (MTB)",
  "NCC Bank",
  "NRB Bank",
  "NRB Commercial Bank",
  "ONE Bank",
  "Padma Bank",
  "Prime Bank",
  "Pubali Bank",
  "Shahjalal Islami Bank",
  "Social Islami Bank (SIBL)",
  "Southeast Bank",
  "South Bangla Agriculture and Commerce Bank",
  "Standard Bank",
  "Trust Bank",
  "United Commercial Bank (UCB)",
  "Uttara Bank",
  "Union Bank",
  "Citizens Bank",
  "Bengal Commercial Bank",
  "Standard Chartered Bank",
  "HSBC",
  "Citibank N.A.",
  "Woori Bank",
  "Bank Alfalah",
  "State Bank of India",
  "Habib Bank",
  "National Bank of Pakistan",
  "Other",
];

export type AccountKind = "bkash" | "nagad" | "rocket" | "upay" | "bank";

export const ACCOUNT_KIND_LABEL: Record<AccountKind, string> = {
  bkash: "bKash",
  nagad: "Nagad",
  rocket: "Rocket",
  upay: "Upay",
  bank: "Bank Account",
};
