/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAccountCheckRouteImport } from './routes/_authenticated/account-check'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedClientDuesRouteImport } from './routes/_authenticated/client-dues'
import { Route as AuthenticatedCongratsRouteImport } from './routes/_authenticated/congrats'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDirectoryRouteImport } from './routes/_authenticated/directory'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedShootingsRouteImport } from './routes/_authenticated/shootings'
import { Route as AuthenticatedSmsRouteImport } from './routes/_authenticated/sms'
import { Route as PMemberIdRouteImport } from './routes/p.$memberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountCheckRoute =
  AuthenticatedAccountCheckRouteImport.update({
    id: '/account-check',
    path: '/account-check',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientDuesRoute = AuthenticatedClientDuesRouteImport.update({
  id: '/client-dues',
  path: '/client-dues',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCongratsRoute = AuthenticatedCongratsRouteImport.update({
  id: '/congrats',
  path: '/congrats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDirectoryRoute = AuthenticatedDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShootingsRoute = AuthenticatedShootingsRouteImport.update({
  id: '/shootings',
  path: '/shootings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSmsRoute = AuthenticatedSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PMemberIdRoute = PMemberIdRouteImport.update({
  id: '/p/$memberId',
  path: '/p/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account-check': typeof AuthenticatedAccountCheckRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/client-dues': typeof AuthenticatedClientDuesRoute
  '/congrats': typeof AuthenticatedCongratsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/directory': typeof AuthenticatedDirectoryRoute
  '/members': typeof AuthenticatedMembersRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/shootings': typeof AuthenticatedShootingsRoute
  '/sms': typeof AuthenticatedSmsRoute
  '/p/$memberId': typeof PMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account-check': typeof AuthenticatedAccountCheckRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/client-dues': typeof AuthenticatedClientDuesRoute
  '/congrats': typeof AuthenticatedCongratsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/directory': typeof AuthenticatedDirectoryRoute
  '/members': typeof AuthenticatedMembersRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/shootings': typeof AuthenticatedShootingsRoute
  '/sms': typeof AuthenticatedSmsRoute
  '/p/$memberId': typeof PMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/account-check': typeof AuthenticatedAccountCheckRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/client-dues': typeof AuthenticatedClientDuesRoute
  '/_authenticated/congrats': typeof AuthenticatedCongratsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/directory': typeof AuthenticatedDirectoryRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/shootings': typeof AuthenticatedShootingsRoute
  '/_authenticated/sms': typeof AuthenticatedSmsRoute
  '/p/$memberId': typeof PMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account-check'
    | '/attendance'
    | '/client-dues'
    | '/congrats'
    | '/dashboard'
    | '/directory'
    | '/members'
    | '/payments'
    | '/reports'
    | '/shootings'
    | '/sms'
    | '/p/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account-check'
    | '/attendance'
    | '/client-dues'
    | '/congrats'
    | '/dashboard'
    | '/directory'
    | '/members'
    | '/payments'
    | '/reports'
    | '/shootings'
    | '/sms'
    | '/p/$memberId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/account-check'
    | '/_authenticated/attendance'
    | '/_authenticated/client-dues'
    | '/_authenticated/congrats'
    | '/_authenticated/dashboard'
    | '/_authenticated/directory'
    | '/_authenticated/members'
    | '/_authenticated/payments'
    | '/_authenticated/reports'
    | '/_authenticated/shootings'
    | '/_authenticated/sms'
    | '/p/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PMemberIdRoute: typeof PMemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account-check': {
      id: '/_authenticated/account-check'
      path: '/account-check'
      fullPath: '/account-check'
      preLoaderRoute: typeof AuthenticatedAccountCheckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client-dues': {
      id: '/_authenticated/client-dues'
      path: '/client-dues'
      fullPath: '/client-dues'
      preLoaderRoute: typeof AuthenticatedClientDuesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/congrats': {
      id: '/_authenticated/congrats'
      path: '/congrats'
      fullPath: '/congrats'
      preLoaderRoute: typeof AuthenticatedCongratsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/directory': {
      id: '/_authenticated/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AuthenticatedDirectoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shootings': {
      id: '/_authenticated/shootings'
      path: '/shootings'
      fullPath: '/shootings'
      preLoaderRoute: typeof AuthenticatedShootingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sms': {
      id: '/_authenticated/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof AuthenticatedSmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/p/$memberId': {
      id: '/p/$memberId'
      path: '/p/$memberId'
      fullPath: '/p/$memberId'
      preLoaderRoute: typeof PMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountCheckRoute: typeof AuthenticatedAccountCheckRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedClientDuesRoute: typeof AuthenticatedClientDuesRoute
  AuthenticatedCongratsRoute: typeof AuthenticatedCongratsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDirectoryRoute: typeof AuthenticatedDirectoryRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedShootingsRoute: typeof AuthenticatedShootingsRoute
  AuthenticatedSmsRoute: typeof AuthenticatedSmsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountCheckRoute: AuthenticatedAccountCheckRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedClientDuesRoute: AuthenticatedClientDuesRoute,
  AuthenticatedCongratsRoute: AuthenticatedCongratsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDirectoryRoute: AuthenticatedDirectoryRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedShootingsRoute: AuthenticatedShootingsRoute,
  AuthenticatedSmsRoute: AuthenticatedSmsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PMemberIdRoute: PMemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
